import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/db';

export const dynamic = 'force-dynamic';

function localDateYMD(d: Date) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function startOfDay(dateStr?: string): Date {
  if (dateStr) {
    const [y, m, d] = dateStr.split('-').map(Number);
    return new Date(y, m - 1, d, 0, 0, 0, 0);
  }
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0);
}

function endOfDay(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59, 999);
}

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.tenantId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const tenantId = session.user.tenantId;
    const body = await request.json().catch(() => ({}));
    const targetDate = startOfDay(body.date);
    const targetDateStr = localDateYMD(targetDate);
    const dayEnd = endOfDay(targetDate);

    // Fetch settings
    const tenant = await prisma.tenant.findUnique({
      where: { id: tenantId },
      select: { settings: true },
    });
    const settings = (tenant?.settings as any) ?? {};
    const hkSchedule = settings.housekeepingSchedule ?? {};
    const dailyCleaning = hkSchedule.dailyCleaning ?? { enabled: true };
    const arrivalSetup = hkSchedule.arrivalSetup ?? { enabled: true, priority: 'HIGH' };
    const departureClean = hkSchedule.departureClean ?? { enabled: true, priority: 'HIGH' };
    const laundry = hkSchedule.laundry ?? { mode: 'off' };

    // Existing tasks for the day (to avoid duplicates)
    const existing = await prisma.housekeepingTask.findMany({
      where: {
        tenantId,
        scheduledDate: { gte: targetDate, lte: dayEnd },
        status: { not: 'CANCELLED' },
      },
      select: { roomId: true, taskType: true },
    });
    const existingKey = new Set(existing.map((e: any) => `${e.roomId}:${e.taskType}`));
    const hasTask = (roomId: string, type: string) => existingKey.has(`${roomId}:${type}`);

    const tasksToCreate: any[] = [];

    // ---- OCCUPIED ROOMS → daily cleaning ----
    if (dailyCleaning.enabled !== false) {
      const occupied = await prisma.booking.findMany({
        where: {
          tenantId,
          status: 'CHECKED_IN',
        },
        select: { roomId: true },
      });
      for (const b of occupied) {
        if (!hasTask(b.roomId, 'CLEANING')) {
          tasksToCreate.push({
            tenantId,
            roomId: b.roomId,
            taskType: 'CLEANING',
            priority: 'MEDIUM',
            status: 'PENDING',
            scheduledDate: targetDate,
            description: 'Daily room cleaning',
            autoGenerated: true,
          });
        }
      }
    }

    // ---- ARRIVALS TODAY → room ready / turnover ----
    if (arrivalSetup.enabled !== false) {
      const arrivals = await prisma.booking.findMany({
        where: {
          tenantId,
          status: { in: ['CONFIRMED', 'CHECKED_IN'] },
          checkInDate: { gte: targetDate, lte: dayEnd },
        },
        select: { roomId: true },
      });
      for (const b of arrivals) {
        if (!hasTask(b.roomId, 'TURNOVER')) {
          tasksToCreate.push({
            tenantId,
            roomId: b.roomId,
            taskType: 'TURNOVER',
            priority: arrivalSetup.priority ?? 'HIGH',
            status: 'PENDING',
            scheduledDate: targetDate,
            description: 'Make room ready for new arrival',
            autoGenerated: true,
          });
        }
      }
    }

    // ---- DEPARTURES TODAY → post-checkout clean ----
    if (departureClean.enabled !== false) {
      const departures = await prisma.booking.findMany({
        where: {
          tenantId,
          status: { in: ['CHECKED_IN', 'CHECKED_OUT'] },
          checkOutDate: { gte: targetDate, lte: dayEnd },
        },
        select: { roomId: true },
      });
      for (const b of departures) {
        // Use DEEP_CLEAN for post-departure rooms, avoid dup if same room already has TURNOVER
        if (!hasTask(b.roomId, 'DEEP_CLEAN') && !hasTask(b.roomId, 'TURNOVER')) {
          tasksToCreate.push({
            tenantId,
            roomId: b.roomId,
            taskType: 'DEEP_CLEAN',
            priority: departureClean.priority ?? 'HIGH',
            status: 'PENDING',
            scheduledDate: targetDate,
            description: 'Post-checkout deep clean',
            autoGenerated: true,
          });
        }
      }
    }

    // ---- LAUNDRY ----
    const laundryMode = laundry.mode ?? 'off';
    const shouldRunLaundry = (() => {
      if (laundryMode === 'off' || laundryMode === 'ondemand') return false;
      if (laundryMode === 'daily') return true;
      if (laundryMode === 'weekly') {
        const weekDay = laundry.weekDay ?? 1; // 1 = Monday default
        return targetDate.getDay() === weekDay;
      }
      return false;
    })();

    if (shouldRunLaundry) {
      const occupiedRooms = await prisma.booking.findMany({
        where: { tenantId, status: 'CHECKED_IN' },
        select: { roomId: true },
      });
      for (const b of occupiedRooms) {
        if (!hasTask(b.roomId, 'LAUNDRY')) {
          tasksToCreate.push({
            tenantId,
            roomId: b.roomId,
            taskType: 'LAUNDRY',
            priority: 'MEDIUM',
            status: 'PENDING',
            scheduledDate: targetDate,
            description: `Laundry service (${laundryMode})`,
            autoGenerated: true,
          });
        }
      }
    }

    // Create all tasks
    if (tasksToCreate.length > 0) {
      await prisma.housekeepingTask.createMany({ data: tasksToCreate });
    }

    return NextResponse.json({
      created: tasksToCreate.length,
      date: targetDateStr,
      breakdown: {
        cleaning: tasksToCreate.filter((t) => t.taskType === 'CLEANING').length,
        turnover: tasksToCreate.filter((t) => t.taskType === 'TURNOVER').length,
        deepClean: tasksToCreate.filter((t) => t.taskType === 'DEEP_CLEAN').length,
        laundry: tasksToCreate.filter((t) => t.taskType === 'LAUNDRY').length,
      },
    });
  } catch (error) {
    console.error('Generate housekeeping tasks error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
