'use client';

import { useMemo, useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Plus, Loader2, Clock, CalendarCheck, Zap, Settings2, Sparkles,
  BedDouble, Shirt, Trash2, WashingMachine, ClipboardCheck, Wrench,
} from 'lucide-react';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select';
import { AddTaskModal } from './add-task-modal';

const priorityColors: Record<string, string> = {
  LOW: 'bg-gray-100 text-gray-700',
  MEDIUM: 'bg-yellow-100 text-yellow-800',
  HIGH: 'bg-orange-100 text-orange-800',
  URGENT: 'bg-red-100 text-red-800',
};

const TASK_TYPE_META: Record<string, { label: string; icon: React.ReactNode; color: string }> = {
  CLEANING:    { label: 'Daily Cleaning',   icon: <Sparkles className="h-3.5 w-3.5" />, color: 'text-teal-600' },
  TURNOVER:    { label: 'Room Ready',       icon: <BedDouble className="h-3.5 w-3.5" />, color: 'text-blue-600' },
  DEEP_CLEAN:  { label: 'Post-Checkout',    icon: <Trash2 className="h-3.5 w-3.5" />,   color: 'text-purple-600' },
  LAUNDRY:     { label: 'Laundry',          icon: <WashingMachine className="h-3.5 w-3.5" />, color: 'text-pink-600' },
  MAINTENANCE: { label: 'Maintenance',      icon: <Wrench className="h-3.5 w-3.5" />,   color: 'text-orange-600' },
  INSPECTION:  { label: 'Inspection',       icon: <ClipboardCheck className="h-3.5 w-3.5" />, color: 'text-indigo-600' },
  SETUP:       { label: 'Setup',            icon: <Shirt className="h-3.5 w-3.5" />,    color: 'text-gray-600' },
};

const WEEK_DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

type DateRange = 'today' | 'week' | 'month' | 'all';

interface Task {
  id: string;
  status: string;
  priority: string;
  taskType: string;
  scheduledDate: string | Date;
  completedAt?: string | Date | null;
  notes?: string | null;
  description?: string | null;
  autoGenerated?: boolean;
  room?: { number: string } | null;
  assignedUser?: { name: string | null } | null;
}

interface Room {
  id: string;
  number: string;
}

interface HousekeepingBoardProps {
  tasks: Task[];
  rooms: Room[];
  schedule?: HKSchedule;
}

interface HKSchedule {
  dailyCleaning?: { enabled?: boolean };
  arrivalSetup?: { enabled?: boolean; priority?: string };
  departureClean?: { enabled?: boolean; priority?: string };
  laundry?: { mode?: string; weekDay?: number };
}

const COLUMNS = [
  { key: 'PENDING',     title: 'Pending',     color: 'bg-yellow-50 border-yellow-200' },
  { key: 'IN_PROGRESS', title: 'In Progress',  color: 'bg-blue-50 border-blue-200' },
  { key: 'COMPLETED',   title: 'Completed',    color: 'bg-green-50 border-green-200' },
];

const DATE_FILTERS: { label: string; value: DateRange }[] = [
  { label: 'Today',     value: 'today' },
  { label: 'This Week', value: 'week' },
  { label: 'This Month',value: 'month' },
  { label: 'All Time',  value: 'all' },
];

function startOf(range: DateRange): Date | null {
  const now = new Date();
  if (range === 'today') return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  if (range === 'week') {
    const d = new Date(now);
    d.setDate(d.getDate() - d.getDay());
    d.setHours(0, 0, 0, 0);
    return d;
  }
  if (range === 'month') return new Date(now.getFullYear(), now.getMonth(), 1);
  return null;
}

// ---- Schedule Settings Dialog ----
function ScheduleSettingsDialog({
  open,
  onOpenChange,
  initial,
  onSaved,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  initial: HKSchedule;
  onSaved: () => void;
}) {
  const [s, setS] = useState<HKSchedule>(initial);
  const [saving, setSaving] = useState(false);

  useEffect(() => { if (open) setS(initial); }, [open, initial]);

  const update = (path: string[], value: any) => {
    setS((prev) => {
      const next = JSON.parse(JSON.stringify(prev));
      let cur: any = next;
      for (let i = 0; i < path.length - 1; i++) {
        if (!cur[path[i]]) cur[path[i]] = {};
        cur = cur[path[i]];
      }
      cur[path[path.length - 1]] = value;
      return next;
    });
  };

  async function save() {
    setSaving(true);
    try {
      await fetch('/api/admin/housekeeping/schedule', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(s),
      });
      onSaved();
      onOpenChange(false);
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Settings2 className="h-5 w-5 text-teal-600" />
            Housekeeping Schedule
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-5 py-2">
          {/* Daily Cleaning */}
          <div className="rounded-lg border p-4 space-y-2">
            <div className="flex items-center justify-between">
              <div>
                <p className="font-medium text-sm flex items-center gap-1.5">
                  <Sparkles className="h-4 w-4 text-teal-500" /> Daily Cleaning
                </p>
                <p className="text-xs text-gray-500 mt-0.5">Auto-create cleaning task for every occupied room</p>
              </div>
              <Switch
                checked={s.dailyCleaning?.enabled !== false}
                onCheckedChange={(v) => update(['dailyCleaning', 'enabled'], v)}
              />
            </div>
          </div>

          {/* Arrival Setup */}
          <div className="rounded-lg border p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <p className="font-medium text-sm flex items-center gap-1.5">
                  <BedDouble className="h-4 w-4 text-blue-500" /> Room Ready for Arrivals
                </p>
                <p className="text-xs text-gray-500 mt-0.5">Create "Make room ready" task for arriving guests</p>
              </div>
              <Switch
                checked={s.arrivalSetup?.enabled !== false}
                onCheckedChange={(v) => update(['arrivalSetup', 'enabled'], v)}
              />
            </div>
            {s.arrivalSetup?.enabled !== false && (
              <div className="flex items-center gap-3 pt-1">
                <Label className="text-xs w-16 shrink-0">Priority</Label>
                <Select
                  value={s.arrivalSetup?.priority ?? 'HIGH'}
                  onValueChange={(v) => update(['arrivalSetup', 'priority'], v)}
                >
                  <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="MEDIUM">Medium</SelectItem>
                    <SelectItem value="HIGH">High</SelectItem>
                    <SelectItem value="URGENT">Urgent</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>

          {/* Departure Deep Clean */}
          <div className="rounded-lg border p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <p className="font-medium text-sm flex items-center gap-1.5">
                  <Trash2 className="h-4 w-4 text-purple-500" /> Post-Checkout Deep Clean
                </p>
                <p className="text-xs text-gray-500 mt-0.5">Create deep clean task for rooms with departures</p>
              </div>
              <Switch
                checked={s.departureClean?.enabled !== false}
                onCheckedChange={(v) => update(['departureClean', 'enabled'], v)}
              />
            </div>
            {s.departureClean?.enabled !== false && (
              <div className="flex items-center gap-3 pt-1">
                <Label className="text-xs w-16 shrink-0">Priority</Label>
                <Select
                  value={s.departureClean?.priority ?? 'HIGH'}
                  onValueChange={(v) => update(['departureClean', 'priority'], v)}
                >
                  <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="MEDIUM">Medium</SelectItem>
                    <SelectItem value="HIGH">High</SelectItem>
                    <SelectItem value="URGENT">Urgent</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>

          {/* Laundry */}
          <div className="rounded-lg border p-4 space-y-3">
            <div>
              <p className="font-medium text-sm flex items-center gap-1.5">
                <WashingMachine className="h-4 w-4 text-pink-500" /> Laundry Schedule
              </p>
              <p className="text-xs text-gray-500 mt-0.5">Auto-create laundry tasks for occupied rooms</p>
            </div>
            <div className="flex items-center gap-3">
              <Label className="text-xs w-20 shrink-0">Frequency</Label>
              <Select
                value={s.laundry?.mode ?? 'off'}
                onValueChange={(v) => update(['laundry', 'mode'], v)}
              >
                <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="off">Off (manual only)</SelectItem>
                  <SelectItem value="ondemand">On-demand (button)</SelectItem>
                  <SelectItem value="daily">Daily</SelectItem>
                  <SelectItem value="weekly">Weekly</SelectItem>
                </SelectContent>
              </Select>
            </div>
            {s.laundry?.mode === 'weekly' && (
              <div className="flex items-center gap-3">
                <Label className="text-xs w-20 shrink-0">Day</Label>
                <Select
                  value={String(s.laundry?.weekDay ?? 1)}
                  onValueChange={(v) => update(['laundry', 'weekDay'], Number(v))}
                >
                  <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {WEEK_DAYS.map((d, i) => (
                      <SelectItem key={i} value={String(i)}>{d}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button className="bg-teal-600 hover:bg-teal-700" onClick={save} disabled={saving}>
            {saving ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : null}
            Save Settings
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ---- Main Board ----
export function HousekeepingBoard({ tasks, rooms, schedule: initialSchedule }: HousekeepingBoardProps) {
  const router = useRouter();
  const [addOpen, setAddOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [dateRange, setDateRange] = useState<DateRange>('today');
  const [generating, setGenerating] = useState(false);
  const [genResult, setGenResult] = useState<{ created: number; breakdown: Record<string, number> } | null>(null);
  const [schedule, setSchedule] = useState<HKSchedule>(initialSchedule ?? {});

  const filteredTasks = useMemo(() => {
    const cutoff = startOf(dateRange);
    if (!cutoff) return tasks;
    return tasks.filter((t) => {
      const dateField =
        t.status === 'COMPLETED' && t.completedAt
          ? new Date(t.completedAt)
          : new Date(t.scheduledDate);
      return dateField >= cutoff;
    });
  }, [tasks, dateRange]);

  async function updateStatus(taskId: string, status: string) {
    setBusyId(taskId);
    try {
      const res = await fetch(`/api/admin/housekeeping/${taskId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status }),
      });
      if (!res.ok) throw new Error('Update failed');
      router.refresh();
    } catch (err) {
      console.error(err);
      alert('Failed to update task');
    } finally {
      setBusyId(null);
    }
  }

  async function generateTasks() {
    setGenerating(true);
    setGenResult(null);
    try {
      const res = await fetch('/api/admin/housekeeping/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });
      const data = await res.json();
      setGenResult({ created: data.created, breakdown: data.breakdown ?? {} });
      router.refresh();
    } catch (err) {
      console.error(err);
      alert('Failed to generate tasks');
    } finally {
      setGenerating(false);
    }
  }

  async function refreshSchedule() {
    const res = await fetch('/api/admin/housekeeping/schedule');
    const data = await res.json();
    setSchedule(data.schedule ?? {});
    router.refresh();
  }

  const totalCompleted = tasks.filter((t) => t.status === 'COMPLETED').length;

  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Housekeeping</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            {totalCompleted} completed · {tasks.filter((t) => t.status === 'PENDING').length} pending
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setSettingsOpen(true)}
            className="text-xs"
          >
            <Settings2 className="h-3.5 w-3.5 mr-1.5" />
            Schedule
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={generateTasks}
            disabled={generating}
            className="text-xs border-teal-300 text-teal-700 hover:bg-teal-50"
          >
            {generating ? (
              <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" />
            ) : (
              <Zap className="h-3.5 w-3.5 mr-1.5" />
            )}
            Generate Today&apos;s Tasks
          </Button>
          <Button onClick={() => setAddOpen(true)} className="bg-teal-600 hover:bg-teal-700 text-xs" size="sm">
            <Plus className="h-3.5 w-3.5 mr-1.5" />
            Add Task
          </Button>
        </div>
      </div>

      {/* Generate result banner */}
      {genResult && (
        <div className="mb-4 flex items-center gap-2 px-4 py-2.5 bg-teal-50 border border-teal-200 rounded-lg text-sm text-teal-800">
          <Sparkles className="h-4 w-4 shrink-0 text-teal-600" />
          <span>
            {genResult.created === 0
              ? 'All tasks for today already exist — nothing new created.'
              : `${genResult.created} task${genResult.created !== 1 ? 's' : ''} created:`}
            {genResult.created > 0 && (
              <span className="ml-1 text-teal-600 font-medium">
                {Object.entries(genResult.breakdown)
                  .filter(([, v]) => v > 0)
                  .map(([k, v]) => `${v} ${k.replace(/([A-Z])/g, ' $1').toLowerCase().trim()}`)
                  .join(' · ')}
              </span>
            )}
          </span>
          <button
            onClick={() => setGenResult(null)}
            className="ml-auto text-teal-500 hover:text-teal-700 text-lg leading-none"
          >
            ×
          </button>
        </div>
      )}

      {/* Laundry schedule info */}
      {schedule.laundry?.mode && schedule.laundry.mode !== 'off' && (
        <div className="mb-4 flex items-center gap-2 px-3 py-2 bg-pink-50 border border-pink-100 rounded-lg text-xs text-pink-700">
          <WashingMachine className="h-3.5 w-3.5 shrink-0" />
          <span>
            Laundry: <span className="font-medium capitalize">{schedule.laundry.mode}</span>
            {schedule.laundry.mode === 'weekly' &&
              ` — every ${WEEK_DAYS[schedule.laundry.weekDay ?? 1]}`}
            {schedule.laundry.mode === 'ondemand' && ' — click "Generate" to create manually'}
          </span>
        </div>
      )}

      {/* Date range filter */}
      <div className="flex items-center gap-2 mb-5 p-2 bg-gray-50 rounded-lg border">
        <span className="text-xs text-gray-500 font-medium mr-1">Show:</span>
        {DATE_FILTERS.map((f) => (
          <button
            key={f.value}
            onClick={() => setDateRange(f.value)}
            className={`px-3 py-1 rounded-md text-xs font-medium transition-colors ${
              dateRange === f.value
                ? 'bg-teal-600 text-white shadow-sm'
                : 'text-gray-600 hover:bg-white hover:shadow-sm'
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {COLUMNS.map((col) => {
          const colTasks = filteredTasks.filter((t) => t.status === col.key);
          const totalForCol = tasks.filter((t) => t.status === col.key).length;
          return (
            <div key={col.key} className={`rounded-lg border-2 ${col.color} p-3`}>
              <div className="flex items-center justify-between mb-3 px-1">
                <h2 className="font-semibold text-gray-800">{col.title}</h2>
                <span className="text-xs font-medium bg-white px-2 py-0.5 rounded-full border">
                  {colTasks.length}
                  {dateRange !== 'all' && totalForCol !== colTasks.length && (
                    <span className="text-gray-400"> / {totalForCol}</span>
                  )}
                </span>
              </div>
              <div className="space-y-2">
                {colTasks.length === 0 ? (
                  <p className="text-sm text-gray-400 text-center py-6">No tasks</p>
                ) : (
                  colTasks.map((task) => {
                    const meta = TASK_TYPE_META[task.taskType] ?? {
                      label: task.taskType?.replace(/_/g, ' '),
                      icon: <Sparkles className="h-3.5 w-3.5" />,
                      color: 'text-gray-600',
                    };
                    return (
                      <Card key={task.id} className="hover:shadow-md transition-shadow">
                        <CardContent className="p-3 space-y-2">
                          <div className="flex items-center justify-between">
                            <span className="font-semibold text-sm">
                              Room {task.room?.number ?? '—'}
                            </span>
                            <span
                              className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                                priorityColors[task.priority] || priorityColors.MEDIUM
                              }`}
                            >
                              {task.priority}
                            </span>
                          </div>

                          <div className={`flex items-center gap-1.5 text-xs font-medium ${meta.color}`}>
                            {meta.icon}
                            <span>{meta.label}</span>
                            {task.autoGenerated && (
                              <span className="ml-auto text-[10px] bg-gray-100 text-gray-500 px-1.5 py-0.5 rounded-full">
                                auto
                              </span>
                            )}
                          </div>

                          {task.description && (
                            <p className="text-[11px] text-gray-500 line-clamp-1">{task.description}</p>
                          )}

                          <div className="flex items-center gap-1 text-[11px] text-gray-400">
                            <Clock className="h-3 w-3 shrink-0" />
                            <span>
                              {task.scheduledDate
                                ? new Date(task.scheduledDate).toLocaleDateString()
                                : '—'}
                            </span>
                          </div>

                          {task.status === 'COMPLETED' && task.completedAt && (
                            <div className="flex items-center gap-1 text-[11px] text-green-600">
                              <CalendarCheck className="h-3 w-3 shrink-0" />
                              <span>
                                Done:{' '}
                                {new Date(task.completedAt).toLocaleString([], {
                                  dateStyle: 'short',
                                  timeStyle: 'short',
                                })}
                              </span>
                            </div>
                          )}

                          {task.notes && (
                            <p className="text-[11px] text-gray-500 bg-gray-50 rounded px-2 py-1 line-clamp-2">
                              {task.notes}
                            </p>
                          )}
                          {task.assignedUser?.name && (
                            <p className="text-[11px] text-gray-500">👤 {task.assignedUser.name}</p>
                          )}

                          <div className="flex gap-2 pt-1">
                            {task.status === 'PENDING' && (
                              <Button
                                size="sm"
                                variant="outline"
                                className="h-7 text-xs flex-1"
                                disabled={busyId === task.id}
                                onClick={() => updateStatus(task.id, 'IN_PROGRESS')}
                              >
                                {busyId === task.id ? (
                                  <Loader2 className="h-3 w-3 animate-spin" />
                                ) : (
                                  'Start Task'
                                )}
                              </Button>
                            )}
                            {task.status === 'IN_PROGRESS' && (
                              <Button
                                size="sm"
                                className="h-7 text-xs flex-1 bg-green-600 hover:bg-green-700"
                                disabled={busyId === task.id}
                                onClick={() => updateStatus(task.id, 'COMPLETED')}
                              >
                                {busyId === task.id ? (
                                  <Loader2 className="h-3 w-3 animate-spin" />
                                ) : (
                                  'Mark Done'
                                )}
                              </Button>
                            )}
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })
                )}
              </div>
            </div>
          );
        })}
      </div>

      <AddTaskModal
        open={addOpen}
        onOpenChange={setAddOpen}
        rooms={rooms}
        onCreated={() => router.refresh()}
      />

      <ScheduleSettingsDialog
        open={settingsOpen}
        onOpenChange={setSettingsOpen}
        initial={schedule}
        onSaved={refreshSchedule}
      />
    </div>
  );
}
